from sqlalchemy import Boolean, Column, Integer, String, DateTime, Text, Float
from database import Base

class ChildAttendance(Base):
    __tablename__ = "child_attendance_test"

    id = Column(Integer, primary_key=True, index=True)
    childname = Column(String(45))
    child_attendance_testcol = Column(Integer)

class DailyAttendanceLog(Base):
    __tablename__ = "dailyattendancelog_new"

    Form_ID = Column(String(100), primary_key=True)
    # PO_No = Column(String(100))
    DOR = Column(DateTime)
    # User_ID = Column(String(100))
    Site_ID = Column(String(100))
    Room_ID = Column(String(100))
    # Child_ID = Column(String(100))
    Form_Date = Column(DateTime)
    Log_Type1 = Column(Integer)
    Log_Type2 = Column(Integer)
    Log_Description = Column(Text)
    Timein = Column(String(100))
    Timeout = Column(String(100))
    # Sig_Signin = Column(Text)
    # Signin_Datetime = Column(DateTime)
    # Sig_Signout = Column(Text)
    # Signout_Datetime = Column(DateTime)
    # Signin_User_ID = Column(String(100))
    # Signout_User_ID = Column(String(100))
    Breakfast = Column(Integer)
    Lunch = Column(Integer)
    PM_Snack = Column(Integer)
    # Meal_User_ID = Column(String(100))
    Meal_Confirm_Datetime = Column(DateTime)

class AgencySites(Base):
    __tablename__ = "agencysites"

    Site_ID = Column(String(50), primary_key=True)
    # Site_Code = Column(String(100))
    # Agency_ID = Column(String(50))
    Site_Name = Column(String(200))
    # Site_SName = Column(String(100))
    # Site_CName = Column(String(100))
    Site_Zip = Column(String(50))
    Site_Address = Column(String(500))
    # Site_Tel = Column(String(500))
    # Site_Fax = Column(String(500))
    # Facility_Number = Column(String(100))
    # Funding = Column(Integer)
    # Language_Preference = Column(String(20))
    # Language_Others = Column(String(500))
    # Site_AgeGroup = Column(String(50))
    # Site_Type = Column(Integer)
    # Zoom_ID = Column(String(100))
    # Zoom_Passcode = Column(String(100))
    # Zoom_Link = Column(String(500))
    # Admin_Site_Type = Column(Integer)
    # Preapp_AgeGroup = Column(String(10))
    # HR_Site_Type = Column(Integer)

class AgencySiteRooms(Base):
    __tablename__ = "agencysiterooms"

    Room_ID = Column(String(100), primary_key=True)
    Site_ID = Column(String(100))
    # Site_Code = Column(String(100))
    Room_Name = Column(String(100))
    # Room_Size = Column(Integer)
    Room_AgeGroup = Column(String(50))
    # Zoom_Parent_Mon = Column(String(100))
    # Zoom_Children_Tue = Column(String(100))
    # Zoom_Children_Wed = Column(String(100))
    # Zoom_Children_Thu = Column(String(100))
    # Funding_Source = Column(String(100))
    # DRDP_Switch = Column(Integer)
    # IsFY = Column(Integer)
    # IsPY = Column(Integer)
    # DayYear = Column(Integer)
    # Portal_Password = Column(String(100))

class CenterSupportReport(Base):
    __tablename__ = "centersupportreport"

    Form_ID = Column(String(100), primary_key=True)
    # PO_No = Column(String(100))
    # DOR = Column(DateTime)
    User_ID = Column(String(100))
    Site_ID = Column(String(500))
    Form_Date = Column(DateTime)
    # Support_Type = Column(Integer)
    Start_Time = Column(String(100))
    End_Time = Column(String(100))
    Support_Log = Column(Text)
    Category = Column(String(100))
    # Category_Other = Column(Text)
    OnsiteRemote = Column(Integer)
    # Submit_Status = Column(Integer)
    # Submit_Datetime = Column(DateTime)
    Strategies = Column(String(500))
    Strategies_Other = Column(Text)
    Debrief = Column(String(500))
    # Debrief_Other = Column(Text)
    # AutoSave = Column(Integer)

class LessonPlansPreschool(Base):
    __tablename__ = "lessonplans_2324_preschool"

    Form_ID = Column(String(100), primary_key=True)
    # PO_No = Column(String(100))
    DOR = Column(DateTime)
    # User_ID = Column(String(100))
    Site_ID = Column(String(100))
    Room_ID = Column(String(100))
    WeekCount = Column(Integer)
    # SDate = Column(DateTime)
    Teacher_Name = Column(String(100))
    Study_Topic = Column(String(1000))
    # UUID_Item = Column(String(500))
    Focus_Week = Column(Text)
    IntentionalTeachingCards = Column(Text)
    MightyMinutes = Column(Text)
    Vocabulary = Column(Text)
    Books = Column(Text)
    FamilyEngagement = Column(Text)
    Individualizations = Column(Text)
    # Modification = Column(Text)
    Blocks = Column(Text)
    Science = Column(Text)
    L_Math = Column(Text)
    WaterSensory = Column(Text)
    Writing = Column(Text)
    DramaticPlay = Column(Text)
    Manipulatives = Column(Text)
    Art = Column(Text)
    MusicMovement = Column(Text)
    Library = Column(Text)
    OutdoorClassroom = Column(Text)
    Other = Column(Text)
    Teachers = Column(String(500))
    Enroll_Year = Column(String(100))
    # Duplicate = Column(Integer)
    # Study_Topic_zh = Column(String(1000))
    # Study_Topic_es = Column(String(1000))
    # Focus_Week_zh = Column(Text)
    # Focus_Week_es = Column(Text)
    # IntentionalTeachingCards_zh = Column(Text)
    # IntentionalTeachingCards_es = Column(Text)
    # MightyMinutes_zh = Column(Text)
    # MightyMinutes_es = Column(Text)
    # Vocabulary_zh = Column(Text)
    # Vocabulary_es = Column(Text)
    # Books_zh = Column(Text)
    # Books_es = Column(Text)
    # FamilyEngagement_zh = Column(Text)
    # FamilyEngagement_es = Column(Text)
    # Individualizations_zh = Column(Text)
    # Individualizations_es = Column(Text)
    # Modification_zh = Column(Text)
    # Modification_es = Column(Text)
    # Blocks_zh = Column(Text)
    # Blocks_es = Column(Text)
    # Science_zh = Column(Text)
    # Science_es = Column(Text)
    # L_Math_zh = Column(Text)
    # L_Math_es = Column(Text)
    # WaterSensory_zh = Column(Text)
    # WaterSensory_es = Column(Text)
    # Writing_zh = Column(Text)
    # Writing_es = Column(Text)
    # DramaticPlay_zh = Column(Text)
    # DramaticPlay_es = Column(Text)
    # Manipulatives_zh = Column(Text)
    # Manipulatives_es = Column(Text)
    # Art_zh = Column(Text)
    # Art_es = Column(Text)
    # MusicMovement_zh = Column(Text)
    # MusicMovement_es = Column(Text)
    # Library_zh = Column(Text)
    # Library_es = Column(Text)
    # OutdoorClassroom_zh = Column(Text)
    # OutdoorClassroom_es = Column(Text)
    # Other_zh = Column(Text)
    # Other_es = Column(Text)
    # AutoSave = Column(Integer)

class LessonPlansIT(Base):
    __tablename__ = "lessonplans_2324_it"

    Form_ID = Column(String(100), primary_key=True)
    # PO_No = Column(String(100))
    DOR = Column(DateTime)
    # User_ID = Column(String(100))
    Site_ID = Column(String(100))
    Room_ID = Column(String(100))
    WeekCount = Column(Integer)
    # SDate = Column(DateTime)
    Teacher_Name = Column(String(100))
    Study_Topic = Column(String(1000))
    # UUID_Item = Column(String(500))
    Focus_Week = Column(Text)
    IntentionalTeachingCards = Column(Text)
    MightyMinutes = Column(Text)
    Vocabulary = Column(Text)
    Books = Column(Text)
    FamilyEngagement = Column(Text)
    Individualizations = Column(Text)
    Infant_Modification = Column(Text)
    # Modification = Column(Text)
    Blocks = Column(Text)
    ScienceMath = Column(Text)
    MusicMovement = Column(Text)
    WaterSensory = Column(Text)
    Art = Column(Text)
    DramaticPlay = Column(Text)
    Manipulatives = Column(Text)
    OutdoorClassroom = Column(Text)
    Teachers = Column(String(500))
    Enroll_Year = Column(String(100))
    # Duplicate = Column(Integer)
    # Study_Topic_zh = Column(String(1000))
    # Study_Topic_es = Column(String(1000))
    # Focus_Week_zh = Column(Text)
    # Focus_Week_es = Column(Text)
    # IntentionalTeachingCards_zh = Column(Text)
    # IntentionalTeachingCards_es = Column(Text)
    # MightyMinutes_zh = Column(Text)
    # MightyMinutes_es = Column(Text)
    # Vocabulary_zh = Column(Text)
    # Vocabulary_es = Column(Text)
    # Books_zh = Column(Text)
    # Books_es = Column(Text)
    # FamilyEngagement_zh = Column(Text)
    # FamilyEngagement_es = Column(Text)
    # Individualizations_zh = Column(Text)
    # Individualizations_es = Column(Text)
    # Modification_zh = Column(Text)
    # Modification_es = Column(Text)
    # Blocks_zh = Column(Text)
    # Blocks_es = Column(Text)
    # ScienceMath_zh = Column(Text)
    # ScienceMath_es = Column(Text)
    # MusicMovement_zh = Column(Text)
    # MusicMovement_es = Column(Text)
    # WaterSensory_zh = Column(Text)
    # WaterSensory_es = Column(Text)
    # Art_zh = Column(Text)
    # Art_es = Column(Text)
    # DramaticPlay_zh = Column(Text)
    # DramaticPlay_es = Column(Text)
    # Manipulatives_zh = Column(Text)
    # Manipulatives_es = Column(Text)
    # OutdoorClassroom_zh = Column(Text)
    # OutdoorClassroom_es = Column(Text)
    # AutoSave = Column(Integer)

class LessonPlansDetail(Base):
    __tablename__ = "lessonplans_detail"

    Log_ID = Column(String(100), primary_key=True)
    Form_ID = Column(String(100))
    P_No = Column(String(100))
    P_Content = Column(Text)
    # P_Content_zh = Column(Text)
    # P_Content_es = Column(Text)

class DRDPItems(Base):
    __tablename__ = "drdp_items"

    UUID_Item = Column(String(200), primary_key=True)
    # Parent_UUID_Item = Column(String(100))
    # Parent_Item_ID = Column(Text)
    # Item_ID = Column(Text)
    Item_Name = Column(Text)
    # Item_Name_zh = Column(String(200))
    # Item_Name_es = Column(String(200))
    # Item_Type = Column(Text)
    # Item_Version = Column(Text)
    Item_Catagory = Column(Text)  # Note: Misspelled in database as "Catagory" not "Category"
    # Essential = Column(Integer)
    # Essential_Part = Column(Integer)
    # Interim = Column(Integer)
    # Interim_Part = Column(Integer)
    # Option_Numbers = Column(Integer)
    # drdp_itemscol = Column(String(45))
    # Essential_Part_2122 = Column(Integer)
    # Flag_2122 = Column(Integer)
    # Essential_Part_2223 = Column(Integer)
    # Flag_2223 = Column(Integer)
    # Flag_2223_Order2 = Column(Integer)
    # Flag_2223_Order2_IT = Column(Integer)
    # Flag_2324_Order2 = Column(Integer)
    # Flag_2324_Order2_IT = Column(Integer)

class DRDPRecord(Base):
    __tablename__ = "drdp_record"

    Form_ID = Column(String(100), primary_key=True)
    # DRDP_Version = Column(String(100))
    Enroll_Year = Column(String(100))
    # DRDP_Order = Column(Integer)
    Child_ID = Column(String(100))
    DOR = Column(DateTime)
    # User_ID = Column(String(100))
    # Teacher_Name = Column(String(100))
    Site_ID = Column(String(100))
    Room_ID = Column(String(100))
    # Submit_Status = Column(Integer)
    Submit_Datetime = Column(DateTime)
    ATL_REG_1 = Column(Float)
    ATL_REG_2 = Column(Float)
    ATL_REG_3 = Column(Float)
    ATL_REG_4 = Column(Float)
    ATL_REG_5 = Column(Float)
    ATL_REG_6 = Column(Float)
    ATL_REG_7 = Column(Float)
    SED_1 = Column(Float)
    SED_2 = Column(Float)
    SED_3 = Column(Float)
    SED_4 = Column(Float)
    SED_5 = Column(Float)
    LLD_1 = Column(Float)
    LLD_2 = Column(Float)
    LLD_3 = Column(Float)
    LLD_4 = Column(Float)
    LLD_5 = Column(Float)
    LLD_6 = Column(Float)
    LLD_7 = Column(Float)
    LLD_8 = Column(Float)
    LLD_9 = Column(Float)
    LLD_10 = Column(Float)
    ELD_1 = Column(Float)
    ELD_2 = Column(Float)
    ELD_3 = Column(Float)
    ELD_4 = Column(Float)
    COG_1 = Column(Float)
    COG_2 = Column(Float)
    COG_3 = Column(Float)
    COG_4 = Column(Float)
    COG_5 = Column(Float)
    COG_6 = Column(Float)
    COG_7 = Column(Float)
    COG_8 = Column(Float)
    COG_9 = Column(Float)
    COG_10 = Column(Float)
    COG_11 = Column(Float)
    PD_HLTH_1 = Column(Float)
    PD_HLTH_2 = Column(Float)
    PD_HLTH_3 = Column(Float)
    PD_HLTH_4 = Column(Float)
    PD_HLTH_5 = Column(Float)
    PD_HLTH_6 = Column(Float)
    PD_HLTH_7 = Column(Float)
    PD_HLTH_8 = Column(Float)
    PD_HLTH_9 = Column(Float)
    PD_HLTH_10 = Column(Float)
    # HSS_1 = Column(Float)
    # HSS_2 = Column(Float)
    # HSS_3 = Column(Float)
    # HSS_4 = Column(Float)
    # HSS_5 = Column(Float)
    # VPA_1 = Column(Float)
    # VPA_2 = Column(Float)
    # VPA_3 = Column(Float)
    # VPA_4 = Column(Float)
    # EM = Column(Integer)
    # UR = Column(Integer)
    # DRDP_Part = Column(Integer)
    # DRDP_Record_ID = Column(String(100))

# Export all models
__all__ = ['ChildAttendance', 'DailyAttendanceLog', 'AgencySites', 'AgencySiteRooms', 'CenterSupportReport', 'LessonPlansPreschool', 'LessonPlansIT', 'LessonPlansDetail', 'DRDPItems', 'DRDPRecord']